### ISSUE TITLE
'datasets: train: name: FFHQ' in .yml got error: did not find expected key

### ISSUE THREAD

**Issue by Rangooo123** [XPixelGroup/BasicSR#701]
I just run the cfg /home/zhanghang/Diffusion/New Folder/BasicSR/options/train/StyleGAN/train_StyleGAN2_256_Cmul2_FFHQ.yml
and got this:
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping
  in "options/train/ZHSR3/train.yml", line 10, column 5
did not find expected key
  in "options/train/ZHSR3/train.yml", line 62, column 15

**Comment by Rangooo123** [comment]
so I am using ffhq dataset that BASICSR supports. And here's my .yml
```
# general settings
name: train_SR3_16to128_ffhq_zh
model_type: ZHSR3
num_gpu: auto
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: FFHQDataset
    dataroot_gt: dataset/ffhq_16_128/hq
    dataroot_lq: dataset/ffhq_16_128/lq
```
